### ISSUE TITLE
New branch "demo-sdk" featuring One tap

### ISSUE THREAD

**Issue by ndrean** [dwyl/elixir-auth-google-demo#12]
I added a new branch to the demo

**Comment by nelsonic** [comment]
Hi please create a Pull Request from your branch:
https://github.com/dwyl/elixir-auth-google-demo/branches
![please-create-a-pull-request-from-your-branch](https://user-images.githubusercontent.com/194400/197334535-d6fe4b00-7530-40e9-b3fb-a79422c49ce0.png)

Assign to me when you feel it's ready for review. 👌
